services:
  database:
    build:
      context: ./database
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_DB=minigamesdb    
    ports:
      - "5432:5432"
  backend:
    build:
      context: ./backend
    networks:
      - traefik-net
      - backend
    expose:
      - "3000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=postgresql://admin:adminpassword@database:5432/minigamesdb
      - JWT_SECRET=a0c5854f84bba853fdd08c8ecb943a88e500410698c77928b74a2eb5d7ca6443ac6a27313a440d32f1b1ad66709128c52f68410e2b3d94c57a8f8af38696757a
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minigamesBackend.rule=Host(`api.dev.akastler.fr`)"
      - "traefik.http.routers.minigamesBackend.entrypoints=websecure"
      - "traefik.http.routers.minigamesBackend.tls.certresolver=le"
      - "traefik.http.services.minigamesBackend.loadbalancer.server.port=3000"
      # redirect http to https
      - "traefik.http.routers.minigamesBackend-http.rule=Host(`api.dev.akastler.fr`)"
      - "traefik.http.routers.minigamesBackend-http.entrypoints=web"
      - "traefik.http.routers.minigamesBackend-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.docker.network=traefik-net"
  front:
    build:
      context: ./front
    volumes:
      - ./front:/app
    networks:
      - traefik-net
    expose:
      - "3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_URL=http://dev.akastler.fr
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minigamesFrontend.rule=Host(`dev.akastler.fr`)"
      - "traefik.http.routers.minigamesFrontend.entrypoints=websecure"
      - "traefik.http.routers.minigamesFrontend.tls.certresolver=le"
      - "traefik.http.services.minigamesFrontend.loadbalancer.server.port=3000"
      # redirect http to https
      - "traefik.http.routers.minigamesFrontend-http.rule=Host(`dev.akastler.fr`)"
      - "traefik.http.routers.minigamesFrontend-http.entrypoints=web"
      - "traefik.http.routers.minigamesFrontend-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.docker.network=traefik-net"

networks:
  traefik-net:
    external: true
  backend:

volumes:
  db-data: