services:
  database:
    build:
      context: ./database
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}    
    ports:
      - "5432:5432"
    labels:
      - traefik.enable=false
  backend:
    build:
      context: ./backend
    networks:
      - traefik-net
      - backend
    expose:
      - "3000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=${BACK_NODE_ENV}
      - PORT=3000
      - DATABASE_URL=${BACK_DATABASE_URL}
      - JWT_SECRET=${BACK_JWT_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minigamesBackend.rule=Host(`${API_HOST}`)"
      - "traefik.http.routers.minigamesBackend.entrypoints=websecure"
      - "traefik.http.routers.minigamesBackend.tls.certresolver=le"
      - "traefik.http.services.minigamesBackend.loadbalancer.server.port=3000"
      # redirect http to https
      - "traefik.http.routers.minigamesBackend-http.rule=Host(`${API_HOST}`)"
      - "traefik.http.routers.minigamesBackend-http.entrypoints=web"
      - "traefik.http.routers.minigamesBackend-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.docker.network=traefik-net"
  front:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    networks:
      - traefik-net
    expose:
      - "3000"
    environment:
      - NODE_ENV=${FRONT_NODE_ENV}
      - NEXT_PUBLIC_URL=${FRONT_NEXT_PUBLIC_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minigamesFrontend.rule=Host(`${FRONT_HOST}`)"
      - "traefik.http.routers.minigamesFrontend.entrypoints=websecure"
      - "traefik.http.routers.minigamesFrontend.tls.certresolver=le"
      - "traefik.http.services.minigamesFrontend.loadbalancer.server.port=3000"
      # redirect http to https
      - "traefik.http.routers.minigamesFrontend-http.rule=Host(`${FRONT_HOST}`)"
      - "traefik.http.routers.minigamesFrontend-http.entrypoints=web"
      - "traefik.http.routers.minigamesFrontend-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.docker.network=traefik-net"

networks:
  traefik-net:
    external: true
  backend:

volumes:
  db-data: